
name: "Parsing Github commitcounts & stars for 2021 GDSC Soongsil Github Contest"

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *" # Runs every hour, on the hour.

jobs:
  codeTest:
    name: Run GithubParser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        working-directory: "githubObserver"

      - name: Run
        run: python main.py ${{ secrets.A_GITHUB_TOKEN }}
        working-directory: "githubObserver"

      - name: Commit updated newestGithubs.json
        run: |
          git config --local user.email "githubParser.githubaction.bot@noreply.gdscsoongsil.com"
          git config --local user.name "githubParser"
          git commit -m "[GithubActionBot] Update newest github commit/stars" -a || echo "Nothing to update"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.A_GITHUB_TOKEN }}
          branch: main
  
#     #TODO shell 하나 짜서 md 만들고 아래 step 돌려서 profile(banner) table update
#       - name: Push Profile Repository
#         id: push_directory
#         uses: cpina/github-action-push-to-another-repository@main
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-directory: 'resources/output'
#           destination-github-username: 'gdsc-ssu'
#           destination-repository-name: '.github'
#           user-email: carles3@pina.cat
#           commit-message: "[GithubActionBot] Update newest github commit/stars"
#           target-branch: main
